<?php

/**
 * @file
 * Implement hooks and callbacks for the d7csp module.
 */

/**
 * Generate a nonce for the current page load.
 */
function d7csp_nonce(): string {
  $nonce = &drupal_static(__FUNCTION__);
  if (!$nonce) {
    $nonce = drupal_random_key(16);
  }
  return $nonce;
}

/**
 * Implements hook_element_info_alter().
 */
function d7csp_element_info_alter(&$type) {
  $type['scripts']['#pre_render'][] = 'd7csp_pre_render_scripts';
}

/**
 * Callback for #pre_render on scripts.
 *
 * Add a nonce attribute to the script tag.
 */
function d7csp_pre_render_scripts(array $elements) {
  $nonce = d7csp_nonce();
  foreach (['scripts', 'settings'] as $type) {
    foreach (element_children($elements[$type]) as $key) {
      $elements[$type][$key]['#attributes']['nonce'] = $nonce;
    }
  }
  return $elements;
}

/**
 * Collect all hosts configured by modules and themes.
 *
 * @return array
 */
function d7csp_hosts(){
  $hosts = &drupal_static(__FUNCTION__);
  if (is_null($hosts )) {
    $hosts = module_invoke_all('d7csp_hosts');
    drupal_alter('d7csp_hosts', $hosts);
  }
  return $hosts;
}

/**
 * Implements hook_d7csp_hosts().
 */
function d7csp_d7csp_hosts(): array {
  $hosts['script-src'][] = "'nonce-" . d7csp_nonce() . "'";
  return $hosts;
}

/**
 * Implements hook_seckit_options_alter().
 */
function d7csp_seckit_options_alter(array &$options) {
  $csp = &$options['seckit_xss']['csp'];
  $hosts = d7csp_hosts();
  foreach ($hosts as $directive => $host_list) {
    if (empty($csp[$directive])) {
      $csp[$directive] = $csp['default-src'];
    }
    $csp[$directive] .= ' ' . implode(' ', $host_list);
  }
}
